### ISSUE TITLE
Where can we find the one shot model loaded in engine.py?

### ISSUE THREAD

**Issue by aldiak** [HaoXu0507/ISBI2023-One-Shot-WM-Tract-Segmentation#2]
Hi, thank you for making this repository public. Can you please tell me where did you get the one shot model you loaded in engine.py (step3_train)? Thank you

**Comment by HaoXu0507** [comment]
Thank you for your question. You should train the one-shot model by yourself (step-2) and load it in step-3.

**Comment by aldiak** [comment]
Okay, thank you.
